import React, { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

function useCountUp(target, duration = 1800) {
  const [count, setCount] = useState(0);
  const ref = useRef(null);
  useEffect(() => {
    const observer = new IntersectionObserver(([e]) => {
      if (e.isIntersecting) {
        let start = 0;
        const step = target / (duration / 16);
        const timer = setInterval(() => {
          start += step;
          if (start >= target) { setCount(target); clearInterval(timer); }
          else setCount(Math.floor(start));
        }, 16);
        observer.disconnect();
      }
    }, { threshold: 0.5 });
    if (ref.current) observer.observe(ref.current);
    return () => observer.disconnect();
  }, [target, duration]);
  return [count, ref];
}

const testimonials = [
  { name: 'Aditya Seth', role: 'Software, Strategy and AI Initiative', text: 'VeriXa has become indispensable to our compliance workflow. It catches misinformation before it reaches our clients with a precision I have never seen in any other tool.', avatar: 'AS' },
  { name: 'Arnab Basu', role: 'Academic Coordinator at Techno India University', text: 'The claim extraction is extraordinary. What used to take my team three hours of manual fact-checking now takes VeriXa under two minutes. The source citations are impeccable.', avatar: 'AB' },
  { name: 'Arnab Saha', role: 'Senior Programme Coordinator at Techno India University', text: 'We integrated VeriXa into our research pipeline. The confidence scoring system has become the gold standard for how we evaluate information quality across the firm.', avatar: 'AS' },
];

const features = [
  { icon: '⬡', title: 'Precision Claim Extraction', desc: 'Atomic decomposition of complex text into individual verifiable statements using chain-of-thought reasoning. Zero ambiguity.' },
  { icon: '◈', title: 'Real-Time Evidence Retrieval', desc: 'Autonomous web intelligence gathering across authoritative sources. Cross-referenced and ranked by credibility in milliseconds.' },
  { icon: '◉', title: 'Verdict and Confidence Scoring', desc: 'True · False · Partially True · Unverifiable — each with a 0-100 confidence score and transparent reasoning chain.' },
  { icon: '⬟', title: 'AI Origin Detection', desc: 'Probabilistic analysis of whether text was generated by an LLM. Stylometric fingerprinting meets statistical pattern recognition.' },
  { icon: '◇', title: 'URL Article Analysis', desc: 'Paste any news article URL. VeriXa scrapes, extracts, and runs the full verification pipeline in seconds.' },
  { icon: '○', title: 'Conflict Surface Intelligence', desc: 'When sources disagree, VeriXa surfaces the conflict explicitly — never averaging away the truth with false consensus.' },
];

const steps = [
  { num: '01', title: 'Submit Text or URL', desc: 'Paste any article, essay, or paste a link. VeriXa accepts raw text or scrapes content automatically.' },
  { num: '02', title: 'Claims Are Extracted', desc: 'The AI engine decomposes your content into discrete, atomic factual claims — each independently verifiable.' },
  { num: '03', title: 'Evidence Is Retrieved', desc: 'Web intelligence agents formulate targeted queries and cross-reference findings against authoritative sources.' },
  { num: '04', title: 'Accuracy Report Generated', desc: 'A granular report with verdicts, confidence scores, citations, and an overall accuracy score is delivered instantly.' },
];

const plans = [
  {
    name: 'Starter', price: '0', period: 'forever', highlight: false,
    desc: 'For individuals exploring intelligent fact-checking.',
    features: ['10 verifications / month', 'Text input only', 'Basic accuracy report', 'Community support'],
    cta: 'Start Free',
  },
  {
    name: 'Professional', price: '29', period: 'per month', highlight: true,
    desc: 'For journalists, analysts, and serious researchers.',
    features: ['500 verifications / month', 'URL + text input', 'AI text detection', 'Priority support', 'Export reports (PDF)', 'Confidence scoring'],
    cta: 'Payments Beginning Soon',
  },
  {
    name: 'Enterprise', price: 'Custom', period: 'contact us', highlight: false,
    desc: 'For organizations requiring full pipeline integration.',
    features: ['Unlimited verifications', 'REST API access', 'SSO and team accounts', 'Dedicated support', 'SLA guarantees', 'Custom models'],
    cta: 'Payments Beginning Soon',
  },
];

export default function LandingPage() {
  const [darkMode, setDarkMode] = useState(true);
  const [stat1, ref1] = useCountUp(4);
  const [stat2, ref2] = useCountUp(10);

  const T = darkMode ? {
    bg: '#0a0a0f',
    bg2: 'rgba(16,16,23,0.5)',
    text: '#f5f3ef',
    text2: 'rgba(245,243,239,0.65)',
    text3: 'rgba(245,243,239,0.35)',
    border: 'rgba(255,255,255,0.07)',
    cardBg: 'rgba(10,10,15,0.7)',
    heroBg: 'radial-gradient(ellipse 80% 60% at 50% 0%, rgba(201,169,110,0.06) 0%, transparent 70%)',
    statBg: 'rgba(10,10,15,0.8)',
    featureHover: 'rgba(201,169,110,0.03)',
    stepBg: 'rgba(26,26,36,0.6)',
    testimonialBg: 'rgba(22,22,31,0.8)',
    pricingBg: 'rgba(16,16,23,0.8)',
    ctaBg: 'radial-gradient(ellipse 60% 50% at 50% 50%, rgba(201,169,110,0.05) 0%, transparent 70%)',
    sectionBg: 'rgba(16,16,23,0.5)',
    badgeText: '#c9a96e',
    quoteColor: 'rgba(245,243,239,0.65)',
    planFeatureColor: 'rgba(245,243,239,0.65)',
  } : {
    bg: '#f5f4f0',
    bg2: 'rgba(236,234,228,0.8)',
    text: '#111111',
    text2: '#333333',
    text3: '#666666',
    border: 'rgba(0,0,0,0.1)',
    cardBg: '#ffffff',
    heroBg: 'radial-gradient(ellipse 80% 60% at 50% 0%, rgba(201,169,110,0.1) 0%, transparent 70%)',
    statBg: '#ffffff',
    featureHover: 'rgba(201,169,110,0.06)',
    stepBg: '#ffffff',
    testimonialBg: '#ffffff',
    pricingBg: '#ffffff',
    ctaBg: 'radial-gradient(ellipse 60% 50% at 50% 50%, rgba(201,169,110,0.08) 0%, transparent 70%)',
    sectionBg: 'rgba(236,234,228,0.8)',
    badgeText: '#8a6530',
    quoteColor: '#333333',
    planFeatureColor: '#333333',
  };

  return (
    <div style={{ background: T.bg, minHeight: '100vh', transition: 'background 0.3s' }}>
      <style>{`
        @keyframes pulse-gold { 0%,100%{opacity:1} 50%{opacity:0.4} }
        @keyframes shimmer { 0%{background-position:-200% center} 100%{background-position:200% center} }
        @keyframes fadeIn { from{opacity:0} to{opacity:1} }
      `}</style>

      <Navbar darkMode={darkMode} />

      {/* Theme Toggle */}
      <button onClick={() => setDarkMode(!darkMode)}
        style={{ position: 'fixed', bottom: 24, right: 24, zIndex: 999, width: 44, height: 44, borderRadius: '50%', background: darkMode ? 'rgba(201,169,110,0.15)' : 'rgba(201,169,110,0.25)', border: '1px solid rgba(201,169,110,0.4)', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', fontSize: 18, transition: 'all 0.2s', boxShadow: '0 2px 12px rgba(0,0,0,0.15)' }}>
        {darkMode ? '☀️' : '🌙'}
      </button>

      {/* HERO */}
      <section style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative', overflow: 'hidden', padding: '120px 24px 80px' }}>
        <div style={{ position: 'absolute', inset: 0, zIndex: 0, background: T.heroBg, pointerEvents: 'none' }} />
        <div style={{ position: 'absolute', inset: 0, zIndex: 0, opacity: darkMode ? 0.03 : 0.06, backgroundImage: 'linear-gradient(rgba(128,128,128,0.5) 1px, transparent 1px), linear-gradient(90deg, rgba(128,128,128,0.5) 1px, transparent 1px)', backgroundSize: '60px 60px', pointerEvents: 'none' }} />
        <div style={{ maxWidth: 800, margin: '0 auto', textAlign: 'center', position: 'relative', zIndex: 1 }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '6px 16px', border: '1px solid rgba(201,169,110,0.3)', borderRadius: 999, background: 'rgba(201,169,110,0.06)', marginBottom: 28, fontSize: 12, color: T.badgeText, letterSpacing: 1.5, fontWeight: 500, textTransform: 'uppercase', fontFamily: 'DM Sans, sans-serif' }}>
            <span style={{ width: 6, height: 6, borderRadius: '50%', background: '#c9a96e', animation: 'pulse-gold 1.8s infinite', display: 'inline-block' }} />
            Now in public beta
          </div>
          <h1 style={{ fontFamily: 'Cormorant Garamond, serif', fontWeight: 300, fontSize: 'clamp(48px, 7vw, 88px)', lineHeight: 1.08, color: T.text, letterSpacing: -1, marginBottom: 24 }}>
            Truth is not<br />
            <span style={{ fontStyle: 'italic', background: 'linear-gradient(90deg, #c9a96e, #e8d5a3, #c9a96e)', backgroundSize: '200% auto', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', animation: 'shimmer 4s linear infinite' }}>negotiable.</span>
          </h1>
          <p style={{ fontSize: 17, color: T.text2, lineHeight: 1.7, maxWidth: 560, margin: '0 auto 40px', fontWeight: 300 }}>
            VeriXa is the world's most precise AI-powered fact verification engine.
            Extract claims, retrieve evidence, and generate authoritative accuracy reports in seconds.
          </p>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 14, flexWrap: 'wrap' }}>
            <Link to="/verify" style={{ padding: '14px 36px', borderRadius: 8, fontSize: 14, fontWeight: 600, background: 'linear-gradient(135deg, #c9a96e, #a07b42)', border: 'none', color: '#0a0a0f', letterSpacing: 0.5, transition: 'all 0.22s', textDecoration: 'none', display: 'inline-block' }}>Start Verifying Free</Link>
            <a href="#how-it-works" style={{ padding: '14px 36px', borderRadius: 8, fontSize: 14, fontWeight: 500, background: 'transparent', border: `1px solid ${T.border}`, color: T.text, letterSpacing: 0.5, textDecoration: 'none', display: 'inline-block' }}>See How It Works</a>
          </div>
          <div style={{ marginTop: 64, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8, color: T.text3, fontSize: 11, letterSpacing: 2, textTransform: 'uppercase' }}>
            <div style={{ width: 1, height: 40, background: 'linear-gradient(to bottom, rgba(201,169,110,0.4), transparent)' }} />
            <span>Scroll</span>
          </div>
        </div>
      </section>

      {/* STATS */}
      <div style={{ maxWidth: 1200, margin: '0 auto', padding: '0 24px' }}>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 1, background: T.border, borderRadius: 16, overflow: 'hidden', border: `1px solid ${T.border}`, margin: '0 auto 80px', maxWidth: 600 }}>
          <div style={{ padding: '40px 32px', textAlign: 'center', background: T.statBg }} ref={ref1}>
            <div style={{ fontFamily: 'Cormorant Garamond, serif', fontWeight: 300, fontSize: 52, color: '#c9a96e', lineHeight: 1 }}>{stat1}+</div>
            <div style={{ fontSize: 12, color: T.text3, letterSpacing: 1.5, textTransform: 'uppercase', marginTop: 8 }}>Media types available</div>
          </div>
          <div style={{ padding: '40px 32px', textAlign: 'center', background: T.statBg }} ref={ref2}>
            <div style={{ fontFamily: 'Cormorant Garamond, serif', fontWeight: 300, fontSize: 52, color: '#c9a96e', lineHeight: 1 }}>{stat2}+</div>
            <div style={{ fontSize: 12, color: T.text3, letterSpacing: 1.5, textTransform: 'uppercase', marginTop: 8 }}>Claims verified to date</div>
          </div>
        </div>
      </div>

      {/* FEATURES */}
      <section id="features" style={{ padding: '80px 0' }}>
        <div style={{ padding: '0 24px', maxWidth: 1200, margin: '0 auto' }}>
          <p style={{ fontSize: 11, letterSpacing: 3, textTransform: 'uppercase', color: '#c9a96e', marginBottom: 14, fontWeight: 500 }}>Capabilities</p>
          <h2 style={{ fontFamily: 'Cormorant Garamond, serif', fontWeight: 300, fontSize: 'clamp(34px, 5vw, 54px)', lineHeight: 1.1, color: T.text, letterSpacing: -0.5 }}>Engineered for<br />absolute precision.</h2>
          <div style={{ width: 48, height: 1, background: 'linear-gradient(to right, #c9a96e, transparent)', margin: '20px 0' }} />
          <p style={{ fontSize: 16, color: T.text2, lineHeight: 1.7, maxWidth: 520, marginTop: 14, fontWeight: 300 }}>Every component of VeriXa is designed to eliminate misinformation at scale.</p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 1, background: T.border, border: `1px solid ${T.border}`, borderRadius: 16, overflow: 'hidden', marginTop: 60 }}>
            {features.map((f, i) => (
              <div key={i} style={{ padding: '36px 32px', background: T.cardBg, transition: 'background 0.22s' }}
                onMouseEnter={e => e.currentTarget.style.background = T.featureHover}
                onMouseLeave={e => e.currentTarget.style.background = T.cardBg}>
                <span style={{ fontSize: 20, color: '#c9a96e', marginBottom: 20, display: 'block' }}>{f.icon}</span>
                <div style={{ fontFamily: 'Cormorant Garamond, serif', fontWeight: 500, fontSize: 20, color: T.text, marginBottom: 10 }}>{f.title}</div>
                <div style={{ fontSize: 14, color: T.text2, lineHeight: 1.7, fontWeight: 300 }}>{f.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section id="how-it-works" style={{ padding: '80px 0', background: T.sectionBg }}>
        <div style={{ padding: '0 24px', maxWidth: 1200, margin: '0 auto' }}>
          <p style={{ fontSize: 11, letterSpacing: 3, textTransform: 'uppercase', color: '#c9a96e', marginBottom: 14, fontWeight: 500 }}>Process</p>
          <h2 style={{ fontFamily: 'Cormorant Garamond, serif', fontWeight: 300, fontSize: 'clamp(34px, 5vw, 54px)', lineHeight: 1.1, color: T.text }}>From text to truth<br />in four steps.</h2>
          <div style={{ width: 48, height: 1, background: 'linear-gradient(to right, #c9a96e, transparent)', margin: '20px 0' }} />
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 32, marginTop: 60 }}>
            {steps.map((step, i) => (
              <div key={i} style={{ padding: '32px 28px', background: T.stepBg, borderRadius: 14, border: `1px solid ${T.border}`, transition: 'border-color 0.22s, transform 0.22s' }}
                onMouseEnter={e => { e.currentTarget.style.borderColor = 'rgba(201,169,110,0.3)'; e.currentTarget.style.transform = 'translateY(-4px)'; }}
                onMouseLeave={e => { e.currentTarget.style.borderColor = T.border; e.currentTarget.style.transform = 'none'; }}>
                <span style={{ fontFamily: 'Cormorant Garamond, serif', fontWeight: 300, fontSize: 48, color: 'rgba(201,169,110,0.2)', lineHeight: 1, marginBottom: 16, display: 'block' }}>{step.num}</span>
                <div style={{ fontFamily: 'Cormorant Garamond, serif', fontWeight: 500, fontSize: 20, color: T.text, marginBottom: 10 }}>{step.title}</div>
                <div style={{ fontSize: 13, color: T.text2, lineHeight: 1.7, fontWeight: 300 }}>{step.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* TESTIMONIALS */}
      <section id="testimonials" style={{ padding: '80px 0' }}>
        <div style={{ padding: '0 24px', maxWidth: 1200, margin: '0 auto' }}>
          <p style={{ fontSize: 11, letterSpacing: 3, textTransform: 'uppercase', color: '#c9a96e', marginBottom: 14, fontWeight: 500 }}>Testimonials</p>
          <h2 style={{ fontFamily: 'Cormorant Garamond, serif', fontWeight: 300, fontSize: 'clamp(34px, 5vw, 54px)', lineHeight: 1.1, color: T.text }}>Trusted by those who<br />demand accuracy.</h2>
          <div style={{ width: 48, height: 1, background: 'linear-gradient(to right, #c9a96e, transparent)', margin: '20px 0' }} />
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 20, marginTop: 56 }}>
            {testimonials.map((t, i) => (
              <div key={i} style={{ padding: '32px 28px', background: T.testimonialBg, borderRadius: 14, border: `1px solid ${T.border}`, transition: 'border-color 0.22s' }}
                onMouseEnter={e => e.currentTarget.style.borderColor = 'rgba(201,169,110,0.25)'}
                onMouseLeave={e => e.currentTarget.style.borderColor = T.border}>
                <p style={{ fontSize: 14, color: T.quoteColor, lineHeight: 1.8, fontWeight: 300, fontStyle: 'italic', marginBottom: 24 }}>"{t.text}"</p>
                <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                  <div style={{ width: 40, height: 40, borderRadius: '50%', background: 'linear-gradient(135deg, rgba(201,169,110,0.2), rgba(201,169,110,0.05))', border: '1px solid rgba(201,169,110,0.25)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 12, fontWeight: 600, color: '#c9a96e', flexShrink: 0 }}>{t.avatar}</div>
                  <div>
                    <div style={{ fontSize: 13, fontWeight: 600, color: T.text }}>{t.name}</div>
                    <div style={{ fontSize: 11, color: T.text3, marginTop: 2 }}>{t.role}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* PRICING */}
      <section id="pricing" style={{ padding: '80px 0', background: T.sectionBg }}>
        <div style={{ padding: '0 24px', maxWidth: 1200, margin: '0 auto' }}>
          <p style={{ fontSize: 11, letterSpacing: 3, textTransform: 'uppercase', color: '#c9a96e', marginBottom: 14, fontWeight: 500 }}>Pricing</p>
          <h2 style={{ fontFamily: 'Cormorant Garamond, serif', fontWeight: 300, fontSize: 'clamp(34px, 5vw, 54px)', lineHeight: 1.1, color: T.text }}>Simple, transparent<br />pricing.</h2>
          <div style={{ width: 48, height: 1, background: 'linear-gradient(to right, #c9a96e, transparent)', margin: '20px 0' }} />
          <p style={{ fontSize: 16, color: T.text2, lineHeight: 1.7, maxWidth: 520, marginTop: 14, fontWeight: 300 }}>Start free. Scale when you are ready. No hidden fees, no surprises.</p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 20, marginTop: 56, alignItems: 'stretch' }}>
            {plans.map((plan, i) => (
              <div key={i}
                style={{ padding: '36px 30px', borderRadius: 16, border: plan.highlight ? '1px solid rgba(201,169,110,0.35)' : `1px solid ${T.border}`, background: plan.highlight ? (darkMode ? 'rgba(201,169,110,0.04)' : 'rgba(201,169,110,0.06)') : T.pricingBg, position: 'relative', transition: 'transform 0.22s', display: 'flex', flexDirection: 'column' }}
                onMouseEnter={e => e.currentTarget.style.transform = 'translateY(-4px)'}
                onMouseLeave={e => e.currentTarget.style.transform = 'none'}>
                {plan.highlight && <div style={{ position: 'absolute', top: -12, left: '50%', transform: 'translateX(-50%)', padding: '4px 16px', borderRadius: 999, fontSize: 10, fontWeight: 700, background: 'linear-gradient(135deg, #c9a96e, #a07b42)', color: '#0a0a0f', letterSpacing: 1.5, textTransform: 'uppercase', whiteSpace: 'nowrap' }}>Most Popular</div>}
                <div style={{ fontFamily: 'Cormorant Garamond, serif', fontWeight: 500, fontSize: 22, color: T.text, marginBottom: 6 }}>{plan.name}</div>
                <div style={{ fontSize: 13, color: T.text3, lineHeight: 1.5, marginBottom: 28 }}>{plan.desc}</div>
                <div style={{ fontFamily: 'Cormorant Garamond, serif', fontWeight: 300, fontSize: 52, color: T.text, lineHeight: 1 }}>{plan.price === 'Custom' ? 'Custom' : `$${plan.price}`}</div>
                <div style={{ fontSize: 12, color: T.text3, marginTop: 4, marginBottom: 28 }}>{plan.period}</div>
                <ul style={{ listStyle: 'none', marginBottom: 32, flex: 1 }}>
                  {plan.features.map((f, j) => (
                    <li key={j} style={{ fontSize: 13, color: T.planFeatureColor, padding: '7px 0', borderBottom: `1px solid ${T.border}`, display: 'flex', alignItems: 'center', gap: 10 }}>
                      <span style={{ color: '#c9a96e', fontSize: 12, flexShrink: 0 }}>◆</span>{f}
                    </li>
                  ))}
                </ul>
                <Link to="/verify" style={{ marginTop: 'auto' }}>
                  <button style={{ width: '100%', padding: '12px', borderRadius: 8, fontSize: 13, fontWeight: 600, background: plan.highlight ? 'linear-gradient(135deg, #c9a96e, #a07b42)' : 'transparent', border: plan.highlight ? 'none' : `1px solid ${T.border}`, color: plan.highlight ? '#0a0a0f' : T.text, cursor: 'pointer', transition: 'all 0.2s', letterSpacing: 0.3 }}>
                    {plan.cta}
                  </button>
                </Link>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section style={{ padding: '120px 24px', textAlign: 'center', position: 'relative', overflow: 'hidden' }}>
        <div style={{ position: 'absolute', inset: 0, background: T.ctaBg, pointerEvents: 'none' }} />
        <div style={{ position: 'relative', zIndex: 1 }}>
          <h2 style={{ fontFamily: 'Cormorant Garamond, serif', fontWeight: 300, fontSize: 'clamp(38px, 5vw, 64px)', lineHeight: 1.1, color: T.text, maxWidth: 700, margin: '0 auto 20px' }}>Start verifying facts<br />with confidence today.</h2>
          <p style={{ fontSize: 16, color: T.text2, maxWidth: 480, margin: '0 auto 40px', lineHeight: 1.7 }}>Join thousands of journalists, researchers, and enterprises who trust VeriXa to surface truth from noise.</p>
          <Link to="/verify" style={{ padding: '14px 36px', borderRadius: 8, fontSize: 14, fontWeight: 600, background: 'linear-gradient(135deg, #c9a96e, #a07b42)', border: 'none', color: '#0a0a0f', letterSpacing: 0.5, textDecoration: 'none', display: 'inline-block' }}>Launch VeriXa Free</Link>
        </div>
      </section>

      <Footer darkMode={darkMode} />
    </div>
  );
}