/**
 * VeriXa i18n — Multilingual Support
 * Supports: 24 Global Languages
 * Version: 2.4.0 (Full 24-Language Support)
 */

const translations = {
  en: {
    navFeatures: 'Features', navHowItWorks: 'How It Works', navPricing: 'Pricing', navTestimonials: 'Testimonials', navDashboard: 'Dashboard', navExtension: 'Extension', navTrending: 'Trending', signIn: 'Sign In', logout: 'Logout', hi: 'Hi', user: 'User', identityAccess: 'IDENTITY_ACCESS', tools: 'Tools', textVerify: 'Text Verify', account: 'Account', signUp: 'Sign Up', myAccount: 'My Account',
    landingBeta: 'NOW IN PUBLIC BETA', landingHero1: 'Truth is not', landingHero2: 'negotiable.', landingHeroSubtitle: 'VeriXa is the world\'s most precise AI-powered fact verification engine. Extract claims, retrieve evidence, and generate authoritative accuracy reports in seconds.', landingStartFree: 'Start Verifying Free', landingSeeHow: 'See How It Works', landingScroll: 'Scroll',
    inputFormats: 'Input formats supported', verdictTypes: 'Verdict types', aiModels: 'AI models powering engine', avgResponse: 'Avg. response time', livePreview: 'Live Preview', seeAction: 'See VeriXa in action.', poweredByLabel: 'Powered by leading AI infrastructure', capabilitiesLabel: 'Engineering Integrity', engineeredPrecision: 'Engineered for absolute precision.', eliminatingMisinfo: 'Eliminating misinformation. At scale. With absolute rigor.', calibration: 'CALIBRATION', latency: 'LATENCY', integrity: 'INTEGRITY', urlAnalysis: 'URL Deep-Analysis', deepScrapeDesc: 'Advanced scraping of news sites and social platforms.', conflictIntel: 'Conflict Intelligence', conflictDesc: 'Detection of conflicting viewpoints and factual disputes.', howItWorksLabel: 'Operational Intelligence', pathTruth: 'The Path to Absolute Truth.', surgicalExtraction: 'Surgical Extraction', surgicalDesc: 'We intake raw content with zero-loss precision, isolating every potential claim.', evidenceRetrieval: 'Evidence Retrieval', evidenceDesc: 'Our engine cross-references millions of data points to uncover hidden facts.', integrityTest: 'Integrity Stress-Test', integrityDesc: 'Every claim is validated against authoritative sources, eliminating noise.', finalVerdict: 'The Final Verdict', finalDesc: 'You receive a clear, evidence-backed report that serves as the source of truth.',
    testimonialsLabel: 'Testimonials', trustedAccuracy: 'Trusted by those who demand accuracy.', pricingLabel: 'Tiered Access', scaleTruth: 'Scale with absolute truth.', starterPlan: 'Starter', proPlan: 'Professional', enterprisePlan: 'Enterprise', startFreeCTA: 'Start Free', soonCTA: 'Payments Beginning Soon',
    demo1: 'The Eiffel Tower is located in Berlin, Germany.', demo2: 'Water boils at 100°C at standard atmospheric pressure.', demo3: 'The Great Wall of China is visible from space with the naked eye.',
    step1Title: 'Submit', step1Desc: 'Paste text or a URL link.', step2Title: 'Extract', step2Desc: 'AI breaks text into facts.', step3Title: 'Verify', step3Desc: 'Agents gather live evidence.', step4Title: 'Report', step4Desc: 'Get your truth certificate.',
    footerTagline: 'The source of truth in an age of uncertainty.', product: 'Product', company: 'Company', legal: 'Legal', about: 'About', careers: 'Careers', blog: 'Blog', privacy: 'Privacy Policy', terms: 'Terms of Service', security: 'Security', rights: 'All rights reserved.',
    ctaTitle: 'Start verifying facts with confidence today.', ctaSubtitle: 'Join thousands of journalists, researchers, and enterprises who trust VeriXa to surface truth from noise.', ctaBtn: 'Launch VeriXa Free'
  },
  es: {
    navFeatures: 'Características', navHowItWorks: 'Cómo funciona', navPricing: 'Precios', navTestimonials: 'Testimonios', navDashboard: 'Dashboard', navExtension: 'Extensión', navTrending: 'Tendencias', signIn: 'Iniciar sesión', logout: 'Cerrar sesión', hi: 'Hola', user: 'Usuario', identityAccess: 'ACCESO_IDENTIDAD', tools: 'Herramientas', textVerify: 'Verificar Texto', account: 'Cuenta', signUp: 'Registrarse', myAccount: 'Mi Cuenta',
    landingBeta: 'AHORA EN BETA PÚBLICA', landingHero1: 'La verdad no es', landingHero2: 'negociable.', landingHeroSubtitle: 'VeriXa es el motor de verificación de hechos por IA más preciso del mundo. Extraiga afirmaciones, recupere evidencia y genere informes de precisión autorizados en segundos.', landingStartFree: 'Comenzar verificación gratis', landingSeeHow: 'Ver cómo funciona', landingScroll: 'Deslizar',
    inputFormats: 'Formatos de entrada compatibles', verdictTypes: 'Tipos de veredicto', aiModels: 'Modelos de IA', avgResponse: 'Tiempo promedio de respuesta', livePreview: 'Vista previa en vivo', seeAction: 'Ver VeriXa en acción.', poweredByLabel: 'Impulsado por infraestructura de IA líder', capabilitiesLabel: 'Integridad de Ingeniería', engineeredPrecision: 'Diseñado para una precisión absoluta.', eliminatingMisinfo: 'Eliminando la desinformación. A escala. Con rigor absoluto.', calibration: 'CALIBRACIÓN', latency: 'LATENCIA', integrity: 'INTEGRIDAD', urlAnalysis: 'Análisis Profundo de URL', deepScrapeDesc: 'Scrapeo avanzado de sitios de noticias y redes sociales.', conflictIntel: 'Inteligencia de Conflictos', conflictDesc: 'Detección de puntos de vista en conflicto y disputas fácticas.', howItWorksLabel: 'Inteligencia Operacional', pathTruth: 'El camino hacia la verdad absoluta.', surgicalExtraction: 'Extracción quirúrgica', surgicalDesc: 'Recibimos contenido sin pérdida de precisión, aislando cada afirmación.', evidenceRetrieval: 'Recuperación de evidencia', evidenceDesc: 'Nuestro motor cruza millones de datos para descubrir hechos ocultos.', integrityTest: 'Prueba de estrés de integridad', integrityDesc: 'Cada afirmación se valida contra fuentes autorizadas.', finalVerdict: 'El veredicto final', finalDesc: 'Recibe un informe claro y respaldado por evidencia.',
    testimonialsLabel: 'Testimonios', trustedAccuracy: 'Confiado por quienes exigen precisión.', pricingLabel: 'Acceso por niveles', scaleTruth: 'Escala con la verdad absoluta.', starterPlan: 'Starter', proPlan: 'Professional', enterprisePlan: 'Enterprise', startFreeCTA: 'Empezar gratis', soonCTA: 'Pagos próximamente',
    demo1: 'La Torre Eiffel se encuentra en Berlín, Alemania.', demo2: 'El agua hierve a 100°C a presión atmosférica estándar.', demo3: 'La Gran Muralla China es visible desde el espacio a simple vista.',
    step1Title: 'Enviar', step1Desc: 'Pega texto o un enlace URL.', step2Title: 'Extraer', step2Desc: 'IA descompone el texto en hechos.', step3Title: 'Verificar', step3Desc: 'Agentes reúnen evidencia en vivo.', step4Title: 'Reporte', step4Desc: 'Obtén tu certificado de verdad.',
    footerTagline: 'La fuente de la verdad en una era de incertidumbre.', product: 'Producto', company: 'Compañía', legal: 'Legal', about: 'Sobre nosotros', careers: 'Carreras', blog: 'Blog', privacy: 'Política de privacidad', terms: 'Términos de servicio', security: 'Seguridad', rights: 'Todos los derechos reservados.',
    ctaTitle: 'Comienza a verificar hechos con confianza hoy.', ctaSubtitle: 'Únete a miles de periodistas, investigadores y empresas que confían en VeriXa para extraer la verdad del ruido.', ctaBtn: 'Iniciar VeriXa Gratis'
  },
  fr: {
    navFeatures: 'Fonctionnalités', navHowItWorks: 'Comment ça marche', navPricing: 'Tarifs', navTestimonials: 'Témoignages', navDashboard: 'Tableau de bord', navExtension: 'Extension', navTrending: 'Tendances', signIn: 'Se connecter', logout: 'Déconnexion', hi: 'Salut', user: 'Utilisateur', identityAccess: 'ACCÈS_IDENTITÉ', tools: 'Outils', textVerify: 'Vérifier le texte', account: 'Compte', signUp: 'S\'inscrire', myAccount: 'Mon Compte',
    landingBeta: 'ACTUELLEMENT EN BÊTA PUBLIQUE', landingHero1: 'La vérité n\'est pas', landingHero2: 'négociable.', landingHeroSubtitle: 'VeriXa est le moteur de vérification des faits par IA le plus précis au monde. Extrayez des affirmations, récupérez des preuves et générez des rapports de précision faisant autorité en quelques secondes.', landingStartFree: 'Commencer la vérification gratuite', landingSeeHow: 'Voir comment ça marche', landingScroll: 'Défiler',
    inputFormats: 'Formats d\'entrée supportés', verdictTypes: 'Types de verdict', aiModels: 'Modèles d\'IA', avgResponse: 'Temps de réponse moyen', livePreview: 'Aperçu en direct', seeAction: 'Voir VeriXa en action.', poweredByLabel: 'Propulsé par une infrastructure d\'IA de pointe', capabilitiesLabel: 'Intégrité de l\'Ingénierie', engineeredPrecision: 'Conçu pour une précision absolue.', eliminatingMisinfo: 'Éliminer la désinformation. À l\'échelle. Avec une rigueur absolue.', calibration: 'CALIBRAGE', latency: 'LATENCE', integrity: 'INTÉGRITÉ', urlAnalysis: 'Analyse approfondie d\'URL', deepScrapeDesc: 'Scraping avancé de sites d\'actualités et de réseaux sociaux.', conflictIntel: 'Intelligence de Conflit', conflictDesc: 'Détection de points de vue contradictoires et de litiges factuels.', howItWorksLabel: 'Intelligence Opérationnelle', pathTruth: 'Le chemin vers la vérité absolue.', surgicalExtraction: 'Extraction chirurgicale', surgicalDesc: 'Nous recevons le contenu avec une précision sans perte, isolant chaque affirmation.', evidenceRetrieval: 'Récupération de preuves', evidenceDesc: 'Notre moteur croise des millions de données pour découvrir des faits cachés.', integrityTest: 'Stress-test d\'intégrité', integrityDesc: 'Chaque affirmation est validée par rapport à des sources faisant autorité.', finalVerdict: 'Le verdict final', finalDesc: 'Vous recevez un rapport clair, étayé par des preuves, servant de source de vérité.',
    testimonialsLabel: 'Témoignages', trustedAccuracy: 'Approuvé par ceux qui exigent de la précision.', pricingLabel: 'Accès par paliers', scaleTruth: 'Évoluez avec la vérité absolue.', starterPlan: 'Starter', proPlan: 'Professionnel', enterprisePlan: 'Entreprise', startFreeCTA: 'Commencer gratuitement', soonCTA: 'Paiements bientôt disponibles',
    demo1: 'La tour Eiffel est située à Berlin, en Allemagne.', demo2: 'L\'eau bout à 100°C à pression atmosphérique normale.', demo3: 'La Grande Muraille de Chine est visible depuis l\'espace à l\'œil nu.',
    step1Title: 'Soumettre', step1Desc: 'Collez du texte ou un lien URL.', step2Title: 'Extraire', step2Desc: 'L\'IA décompose le texte en faits.', step3Title: 'Vérifier', step3Desc: 'Des agents rassemblent des preuves en direct.', step4Title: 'Rapport', step4Desc: 'Obtenez votre certificat de vérité.',
    footerTagline: 'La source de vérité dans une ère d\'incertitude.', product: 'Produit', company: 'Entreprise', legal: 'Légal', about: 'À propos', careers: 'Carrières', blog: 'Blog', privacy: 'Politique de confidentialité', terms: 'Conditions d\'utilisation', security: 'Sécurité', rights: 'Tous droits réservés.',
    ctaTitle: 'Commencez à vérifier les faits avec confiance dès aujourd\'hui.', ctaSubtitle: 'Rejoignez des milliers de journalistes, de chercheurs et d\'entreprises qui font confiance à VeriXa pour faire émerger la vérité du bruit.', ctaBtn: 'Lancer VeriXa Gratuitement'
  },
  de: {
    navFeatures: 'Funktionen', navHowItWorks: 'Wie es funktioniert', navPricing: 'Preise', navTestimonials: 'Referenzen', navDashboard: 'Dashboard', navExtension: 'Erweiterung', navTrending: 'Trends', signIn: 'Anmelden', logout: 'Abmelden', hi: 'Hallo', user: 'Benutzer', identityAccess: 'IDENTITÄTS_ZUGANG', tools: 'Werkzeuge', textVerify: 'Text prüfen', account: 'Konto', signUp: 'Registrieren', myAccount: 'Mein Konto',
    landingBeta: 'JETZT IN DER ÖFFENTLICHEN BETA', landingHero1: 'Wahrheit ist nicht', landingHero2: 'verhandelbar.', landingHeroSubtitle: 'VeriXa ist die weltweit präziseste KI-gestützte Faktenprüfungs-Engine. Extrahieren Sie Behauptungen, rufen Sie Beweise ab und erstellen Sie in Sekundenschnelle maßgebliche Genauigkeitsberichte.', landingStartFree: 'Kostenlos prüfen', landingSeeHow: 'Wie es funktioniert', landingScroll: 'Scrollen',
    inputFormats: 'Unterstützte Eingabeformate', verdictTypes: 'Urteilstypen', aiModels: 'KI-Modelle', avgResponse: 'Durchschn. Antwortzeit', livePreview: 'Live-Vorschau', seeAction: 'VeriXa in Aktion sehen.', poweredByLabel: 'Unterstützt von führender KI-Infrastruktur', capabilitiesLabel: 'Technische Integrität', engineeredPrecision: 'Entwickelt für absolute Präzision.', eliminatingMisinfo: 'Fehlinformationen eliminieren. Skalierbar. Mit absoluter Strenge.', calibration: 'KALIBRIERUNG', latency: 'LATENZ', integrity: 'INTEGRITÄT', urlAnalysis: 'Tiefgehende URL-Analyse', deepScrapeDesc: 'Erweitertes Scraping von Nachrichtenseiten und sozialen Plattformen.', conflictIntel: 'Konflikt-Intelligenz', conflictDesc: 'Erkennung widersprüchlicher Standpunkte und faktischer Streitigkeiten.', howItWorksLabel: 'Operative Intelligenz', pathTruth: 'Der Weg zur absoluten Wahrheit.', surgicalExtraction: 'Chirurgische Extraktion', surgicalDesc: 'Wir nehmen Rohinhalte mit verlustfreier Präzision auf und isolieren jede Behauptung.', evidenceRetrieval: 'Beweisabruf', evidenceDesc: 'Unsere Engine gleicht Millionen von Datenpunkten ab, um verborgene Fakten aufzudecken.', integrityTest: 'Integritäts-Stresstest', integrityDesc: 'Jede Behauptung wird gegen maßgebliche Quellen validiert.', finalVerdict: 'Das endgültige Urteil', finalDesc: 'Sie erhalten einen klaren, evidenzbasierten Bericht als Quelle der Wahrheit.',
    testimonialsLabel: 'Referenzen', trustedAccuracy: 'Vertraut von denen, die Genauigkeit fordern.', pricingLabel: 'Gestufter Zugang', scaleTruth: 'Mit absoluter Wahrheit skalieren.', starterPlan: 'Starter', proPlan: 'Professional', enterprisePlan: 'Enterprise', startFreeCTA: 'Kostenlos starten', soonCTA: 'Zahlungen bald möglich',
    demo1: 'Der Eiffelturm befindet sich in Berlin, Deutschland.', demo2: 'Wasser siedet bei 100°C bei normalem Luftdruck.', demo3: 'Die Chinesische Mauer ist vom Weltraum aus mit bloßem Auge sichtbar.',
    step1Title: 'Einreichen', step1Desc: 'Text oder URL-Link einfügen.', step2Title: 'Extrahieren', step2Desc: 'KI zerlegt Text in Fakten.', step3Title: 'Verifizieren', step3Desc: 'Agenten sammeln Live-Beweise.', step4Title: 'Bericht', step4Desc: 'Wahrheitszertifikat erhalten.',
    footerTagline: 'Die Quelle der Wahrheit in einer Zeit der Ungewissheit.', product: 'Produkt', company: 'Unternehmen', legal: 'Rechtliches', about: 'Über uns', careers: 'Karriere', blog: 'Blog', privacy: 'Datenschutz', terms: 'Nutzungsbedingungen', security: 'Sicherheit', rights: 'Alle Rechte vorbehalten.',
    ctaTitle: 'Beginnen Sie noch heute damit, Fakten mit Zuversicht zu prüfen.', ctaSubtitle: 'Schließen Sie sich Tausenden von Journalisten, Forschern und Unternehmen an, die VeriXa vertrauen, um die Wahrheit aus dem Lärm zu filtern.', ctaBtn: 'VeriXa kostenlos starten'
  },
  hi: {
    navFeatures: 'विशेषताएं', navHowItWorks: 'यह कैसे काम करता है', navPricing: 'मूल्य निर्धारण', navTestimonials: 'प्रशंसापत्र', navDashboard: 'डैशबोर्ड', navExtension: 'एक्सटेंशन', navTrending: 'ट्रेंडिंग', signIn: 'साइन इन करें', logout: 'लॉग आउट', hi: 'नमस्ते', user: 'उपयोगकर्ता', identityAccess: 'पहचान_पहुँच', tools: 'उपकरण', textVerify: 'टेक्स्ट सत्यापन', account: 'खाता', signUp: 'साइन अप करें', myAccount: 'मेरा खाता',
    landingBeta: 'अब सार्वजनिक बीटा में', landingHero1: 'सत्य', landingHero2: 'परक्राम्य नहीं है।', landingHeroSubtitle: 'VeriXa दुनिया का सबसे सटीक AI-संचालित तथ्य सत्यापन इंजन है। दावों को निकालें, साक्ष्य प्राप्त करें और सेकंडों में आधिकारिक सटीकता रिपोर्ट तैयार करें।', landingStartFree: 'मुफ्त सत्यापन शुरू करें', landingSeeHow: 'देखें यह कैसे काम करता है', landingScroll: 'स्क्रॉल करें',
    inputFormats: 'इनपुट प्रारूप समर्थित', verdictTypes: 'निर्णय प्रकार', aiModels: 'AI मॉडल', avgResponse: 'औसत प्रतिक्रिया समय', livePreview: 'लाइव पूर्वावलोकन', seeAction: 'VeriXa को क्रिया में देखें।', poweredByLabel: 'अग्रणी AI बुनियादी ढांचे द्वारा संचालित', capabilitiesLabel: 'इंजीनियरिंग अखंडता', engineeredPrecision: 'पूर्ण सटीकता के लिए इंजीनियर किया गया।', eliminatingMisinfo: 'गलत सूचना को खत्म करना। बड़े पैमाने पर। पूर्ण कठोरता के साथ।', calibration: 'अंशांकन', latency: 'विलंबता', integrity: 'अखंडता', urlAnalysis: 'URL गहन विश्लेषण', deepScrapeDesc: 'समाचार साइटों और सोशल प्लेटफॉर्म की उन्नत स्क्रैपिंग।', conflictIntel: 'संघर्ष इंटेलिजेंस', conflictDesc: 'परस्पर विरोधी दृष्टिकोणों और तथ्यात्मक विवादों का पता लगाना।', howItWorksLabel: 'परिचालन इंटेलिजेंस', pathTruth: 'परम सत्य का मार्ग।', surgicalExtraction: 'सर्जिकल निष्कर्षण', surgicalDesc: 'हम शून्य-नुकसान सटीकता के साथ कच्ची सामग्री लेते हैं, हर संभावित दावे को अलग करते हैं।', evidenceRetrieval: 'साक्ष्य पुनर्प्राप्ति', evidenceDesc: 'हमारा इंजन छिपे हुए तथ्यों को उजागर करने के लिए लाखों डेटा बिंदुओं को क्रॉस-रेफरेंस करता है।', integrityTest: 'अखंडता तनाव-परीक्षण', integrityDesc: 'शोर को खत्म करते हुए, हर दावे को आधिकारिक स्रोतों के खिलाफ मान्य किया जाता है।', finalVerdict: 'अंतिम निर्णय', finalDesc: 'आपको एक स्पष्ट, साक्ष्य-आधारित रिपोर्ट प्राप्त होती है जो सत्य के स्रोत के रूप में कार्य करती।',
    testimonialsLabel: 'प्रशंसापत्र', trustedAccuracy: 'उन लोगों द्वारा विश्वसनीय जो सटीकता की मांग करते हैं।', pricingLabel: 'स्तरित पहुँच', scaleTruth: 'पूर्ण सत्य के साथ स्केल करें।', starterPlan: 'स्टार्टर', proPlan: 'प्रोफेशनल', enterprisePlan: 'एंटरप्राइज', startFreeCTA: 'मुफ्त शुरू करें', soonCTA: 'भुगतान जल्द ही शुरू होगा',
    demo1: 'एफिल टॉवर बर्लिन, जर्मनी में स्थित है।', demo2: 'पानी सामान्य वायुमंडलीय दबाव पर 100°C पर उबलता है।', demo3: 'चीन की महान दीवार अंतरिक्ष से नग्न आंखों से दिखाई देती है।',
    step1Title: 'जमा करें', step1Desc: 'टेक्स्ट या URL लिंक पेस्ट करें।', step2Title: 'निकालें', step2Desc: 'AI टेक्स्ट को तथ्यों में तोड़ता है।', step3Title: 'सत्यापित करें', step3Desc: 'एजेंट लाइव साक्ष्य इकट्ठा करते हैं।', step4Title: 'रिपोर्ट', step4Desc: 'अपना सत्य प्रमाण पत्र प्राप्त करें।',
    footerTagline: 'अनिश्चितता के युग में सत्य का स्रोत।', product: 'उत्पाद', company: 'कंपनी', legal: 'कानूनी', about: 'के बारे में', careers: 'करियर', blog: 'ब्लॉग', privacy: 'गोपनीयता नीति', terms: 'सेवा की शर्तें', security: 'सुरक्षा', rights: 'सर्वाधिकार सुरक्षित।',
    ctaTitle: 'आज ही विश्वास के साथ तथ्यों की पुष्टि करना शुरू करें।', ctaSubtitle: 'उन हजारों पत्रकारों, शोधकर्ताओं और उद्यमों में शामिल हों जो शोर से सच्चाई को सतह पर लाने के लिए VeriXa पर भरोसा करते हैं।', ctaBtn: 'VeriXa मुफ्त में लॉन्च करें'
  },
  bn: {
    navFeatures: 'বৈশিষ্ট্য', navHowItWorks: 'কিভাবে এটি কাজ করে', navPricing: 'মূল্য নির্ধারণ', navTestimonials: 'প্রশংসাপত্র', navDashboard: 'ড্যাশবোর্ড', navExtension: 'এক্সটেনশন', navTrending: 'ট্রেন্ডিং', signIn: 'সাইন ইন', logout: 'লগ আউট', hi: 'হ্যালো', user: 'ব্যবহারকারী', identityAccess: 'পরিচয়_অ্যাক্সেস', tools: 'সরঞ্জাম', textVerify: 'টেক্সট যাচাই', account: 'অ্যাকাউন্ট', signUp: 'সাইন আপ', myAccount: 'আমার অ্যাকাউন্ট',
    landingBeta: 'এখন পাবলিক বিটাতে', landingHero1: 'সত্য', landingHero2: 'আলোচনা সাপেক্ষ নয়।', landingHeroSubtitle: 'VeriXa বিশ্বের সবচেয়ে নির্ভুল AI-চালিত তথ্য যাচাইকরণ ইঞ্জিন। দাবিগুলি বের করুন, প্রমাণ সংগ্রহ করুন এবং সেকেন্ডের মধ্যে নির্ভরযোগ্য নির্ভুলতা রিপোর্ট তৈরি করুন।', landingStartFree: 'বিনামূল্যে যাচাই শুরু করুন', landingSeeHow: 'দেখুন কিভাবে কাজ করে', landingScroll: 'স্ক্রল করুন',
    inputFormats: 'সমর্থিত ইনপুট ফরম্যাট', verdictTypes: 'রায় প্রকার', aiModels: 'AI মডেল', avgResponse: 'গড় প্রতিক্রিয়া সময়', livePreview: 'লাইভ প্রিভিউ', seeAction: 'VeriXa কার্যকরভাবে দেখুন।', poweredByLabel: 'শীর্ষস্থানীয় AI অবকাঠামো দ্বারা চালিত', capabilitiesLabel: 'ইঞ্জিনিয়ারিং সততা', engineeredPrecision: 'পরম নির্ভুলতার জন্য তৈরি।', eliminatingMisinfo: 'ভুল তথ্য নির্মূল করা। ব্যাপক পরিসরে। কঠোরতার সাথে।', calibration: 'ক্যালিব্রেশন', latency: 'ল্যাটেন্সি', integrity: 'সততা', urlAnalysis: 'URL গভীর বিশ্লেষণ', deepScrapeDesc: 'নিউজ সাইট এবং সোশ্যাল প্ল্যাটফর্মের উন্নত স্ক্র্যাপিং।', conflictIntel: 'দ্বন্দ্ব বুদ্ধিমত্তা', conflictDesc: 'পরস্পরবিরোধী দৃষ্টিভঙ্গি এবং তথ্যগত বিরোধ সনাক্তকরণ।', howItWorksLabel: 'অপারেশনাল ইন্টেলিজেন্স', pathTruth: 'পরম সত্যের পথ।', surgicalExtraction: 'সার্জিক্যাল এক্সট্রাকশন', surgicalDesc: 'আমরা জিরো-লস নির্ভুলতার সাথে কাঁচা কন্টেন্ট গ্রহণ করি, প্রতিটি সম্ভাব্য দাবি আলাদা করি।', evidenceRetrieval: 'প্রমাণ পুনরুদ্ধার', evidenceDesc: 'আমাদের ইঞ্জিন লুকানো তথ্য উন্মোচন করতে লক্ষ লক্ষ ডেটা পয়েন্ট ক্রস-রেফারেন্স করে।', integrityTest: 'সততা স্ট্রেস-টেস্ট', integrityDesc: 'প্রতিটি দাবি নির্ভরযোগ্য উৎসের বিপরীতে যাচাই করা হয়, বিভ্রান্তি দূর করে।', finalVerdict: 'চূড়ান্ত রায়', finalDesc: 'আপনি একটি পরিষ্কার, প্রমাণ-ভিত্তিক রিপোর্ট পাবেন যা সত্যের উৎস হিসেবে কাজ করবে।',
    testimonialsLabel: 'প্রশংসাপত্র', trustedAccuracy: 'যারা নির্ভুলতা চান তাদের দ্বারা বিশ্বস্ত।', pricingLabel: 'স্তরযুক্ত অ্যাক্সেস', scaleTruth: 'পরম সত্যের সাথে এগিয়ে যান।', starterPlan: 'স্টার্টার', proPlan: 'প্রফেশনাল', enterprisePlan: 'এন্টারপ্রাইজ', startFreeCTA: 'বিনামূল্যে শুরু করুন', soonCTA: 'পেমেন্ট শীঘ্রই শুরু হবে',
    demo1: 'আইফেল টাওয়ার জার্মানির বার্লিনে অবস্থিত।', demo2: 'স্বাভাবিক বায়ুমণ্ডলীয় চাপে জল ১০০° সেলসিয়াসে ফোটে।', demo3: 'চীনের মহাপ্রাচীর মহাকাশ থেকে খালি চোখে দেখা যায়।',
    step1Title: 'জমা দিন', step1Desc: 'টেক্সট বা URL লিঙ্ক পেস্ট করুন।', step2Title: 'বের করুন', step2Desc: 'AI টেক্সটকে তথ্যে বিভক্ত করে।', step3Title: 'যাচাই করুন', step3Desc: 'এজেন্টরা সরাসরি প্রমাণ সংগ্রহ করে।', step4Title: 'রিপোর্ট', step4Desc: 'আপনার সত্যের শংসাপত্র পান।',
    footerTagline: 'অনিশ্চয়তার যুগে সত্যের উৎস।', product: 'পণ্য', company: 'কোম্পানি', legal: 'আইনি', about: 'সম্পর্কে', careers: 'ক্যারিয়ার', blog: 'ব্লগ', privacy: 'গোপনীয়তা নীতি', terms: 'পরিষেবার শর্তাবলী', security: 'নিরাপত্তা', rights: 'সর্বস্বত্ব সংরক্ষিত।',
    ctaTitle: 'আজই আত্মবিশ্বাসের সাথে তথ্য যাচাই করা শুরু করুন।', ctaSubtitle: 'হাজার হাজার সাংবাদিক, গবেষক এবং উদ্যোগের সাথে যোগ দিন যারা বিভ্রান্তি থেকে সত্য খুঁজে পেতে VeriXa-এর ওপর আস্থা রাখেন।', ctaBtn: 'বিনামূল্যে VeriXa শুরু করুন'
  },
  it: {
    navFeatures: 'Caratteristiche', navHowItWorks: 'Come funziona', navPricing: 'Prezzi', navTestimonials: 'Testimonianze', navDashboard: 'Dashboard', navExtension: 'Estensione', navTrending: 'Tendenze', signIn: 'Accedi', logout: 'Esci', hi: 'Ciao', user: 'Utente', identityAccess: 'ACCESSO_IDENTITÀ', tools: 'Strumenti', textVerify: 'Verifica Testo', account: 'Account', signUp: 'Registrati', myAccount: 'Il mio Account',
    landingBeta: 'ORA IN BETA PUBBLICA', landingHero1: 'La verità non è', landingHero2: 'negoziabile.', landingHeroSubtitle: 'VeriXa è il motore di verifica dei fatti basato su IA più preciso al mondo. Estrai affermazioni, recupera prove e genera rapporti di accuratezza autorevoli in pochi secondi.', landingStartFree: 'Inizia la verifica gratuita', landingSeeHow: 'Scopri come funziona', landingScroll: 'Scorri',
    inputFormats: 'Formati di input supportati', verdictTypes: 'Tipi di verdetto', aiModels: 'Modelli di IA', avgResponse: 'Tempo di risposta medio', livePreview: 'Anteprima dal vivo', seeAction: 'Guarda VeriXa in azione.', poweredByLabel: 'Alimentato dalle principali infrastrutture IA', capabilitiesLabel: 'Integrità Ingegneristica', engineeredPrecision: 'Progettato per la precisione assoluta.', eliminatingMisinfo: 'Eliminare la disinformazione. Su scala. Con rigore assoluto.', calibration: 'CALIBRAZIONE', latency: 'LATENZA', integrity: 'INTEGRITÀ', urlAnalysis: 'Analisi approfondita URL', deepScrapeDesc: 'Scraping avanzato di siti di notizie e piattaforme social.', conflictIntel: 'Intelligence sui conflitti', conflictDesc: 'Rilevamento di punti di vista contrastanti e dispute fattuali.', howItWorksLabel: 'Intelligenza Operativa', pathTruth: 'Il percorso verso la verità assoluta.', surgicalExtraction: 'Estrazione chirurgica', surgicalDesc: 'Riceviamo contenuti grezzi con precisione senza perdite, isolando ogni potenziale affermazione.', evidenceRetrieval: 'Recupero prove', evidenceDesc: 'Il nostro motore incrocia milioni di punti dati per scoprire fatti nascosti.', integrityTest: 'Stress-test di integrità', integrityDesc: 'Ogni affermazione è convalidata rispetto a fonti autorevoli, eliminando il rumore.', finalVerdict: 'Il verdetto finale', finalDesc: 'Ricevi un rapporto chiaro e supportato da prove che funge da fonte di verità.',
    testimonialsLabel: 'Testimonianze', trustedAccuracy: 'Scelto da chi esige accuratezza.', pricingLabel: 'Accesso a livelli', scaleTruth: 'Scala con la verità assoluta.', starterPlan: 'Starter', proPlan: 'Professionale', enterprisePlan: 'Enterprise', startFreeCTA: 'Inizia gratis', soonCTA: 'Pagamenti a breve',
    demo1: 'La Torre Eiffel si trova a Berlino, in Germania.', demo2: 'L\'acqua bolle a 100°C alla pressione atmosferica standard.', demo3: 'La Grande Muraglia Cinese è visibile dallo spazio a occhio nudo.',
    step1Title: 'Invia', step1Desc: 'Incolla il testo o un link URL.', step2Title: 'Estrai', step2Desc: 'L\'IA scompone il testo in fatti.', step3Title: 'Verifica', step3Desc: 'Gli agenti raccolgono prove dal vivo.', step4Title: 'Rapporto', step4Desc: 'Ottieni il tuo certificato di verità.',
    footerTagline: 'La fonte della verità in un\'era di incertezza.', product: 'Prodotto', company: 'Azienda', legal: 'Legale', about: 'Chi siamo', careers: 'Carriere', blog: 'Blog', privacy: 'Privacy', terms: 'Termini', security: 'Sicurezza', rights: 'Tutti i diritti riservati.',
    ctaTitle: 'Inizia oggi stesso a verificare i fatti con sicurezza.', ctaSubtitle: 'Unisciti a migliaia di giornalisti, ricercatori e aziende che si affidano a VeriXa per far emergere la verità dal rumore.', ctaBtn: 'Avvia VeriXa Gratis'
  },
  pt: {
    navFeatures: 'Funcionalidades', navHowItWorks: 'Como funciona', navPricing: 'Preços', navTestimonials: 'Depoimentos', navDashboard: 'Painel', navExtension: 'Extensão', navTrending: 'Tendências', signIn: 'Entrar', logout: 'Sair', hi: 'Olá', user: 'Usuário', identityAccess: 'ACESSO_IDENTIDADE', tools: 'Ferramentas', textVerify: 'Verificar Texto', account: 'Conta', signUp: 'Cadastrar', myAccount: 'Minha Conta',
    landingBeta: 'AGORA EM BETA PÚBLICA', landingHero1: 'A verdade não é', landingHero2: 'negociável.', landingHeroSubtitle: 'VeriXa é o motor de verificação de factos por IA mais preciso do mundo. Extraia afirmações, recupere provas e gere relatórios de precisão fidedignos em segundos.', landingStartFree: 'Iniciar Verificação Gratuita', landingSeeHow: 'Veja como funciona', landingScroll: 'Rolar',
    inputFormats: 'Formatos de entrada suportados', verdictTypes: 'Tipos de veredicto', aiModels: 'Modelos de IA', avgResponse: 'Tempo de resposta médio', livePreview: 'Visualização ao vivo', seeAction: 'Veja o VeriXa em ação.', poweredByLabel: 'Alimentado por infraestrutura de IA líder', capabilitiesLabel: 'Integridade de Engenharia', engineeredPrecision: 'Projetado para precisão absoluta.', eliminatingMisinfo: 'Eliminando a desinformação. À escala. Com rigor absoluto.', calibration: 'CALIBRAÇÃO', latency: 'LATÊNCIA', integrity: 'INTEGRIDADE', urlAnalysis: 'Análise profunda de URL', deepScrapeDesc: 'Scraping avançado de sites de notícias e plataformas sociais.', conflictIntel: 'Inteligência de Conflito', conflictDesc: 'Deteção de pontos de vista conflituosos e disputas factuais.', howItWorksLabel: 'Inteligência Operacional', pathTruth: 'O caminho para a verdade absoluta.', surgicalExtraction: 'Extração cirúrgica', surgicalDesc: 'Recebemos conteúdo bruto com precisão zero de perda, isolando cada afirmação potencial.', evidenceRetrieval: 'Recuperação de evidências', evidenceDesc: 'O nosso motor cruza milhões de pontos de dados para descobrir factos ocultos.', integrityTest: 'Teste de stress de integridade', integrityDesc: 'Cada afirmação é validada contra fontes fidedignas, eliminando o ruído.', finalVerdict: 'O veredicto final', finalDesc: 'Recebe um relatório claro, baseado em evidências, que serve como fonte da verdade.',
    testimonialsLabel: 'Depoimentos', trustedAccuracy: 'Confiado por quem exige precisão.', pricingLabel: 'Acesso por níveis', scaleTruth: 'Escala com a verdade absoluta.', starterPlan: 'Starter', proPlan: 'Profissional', enterprisePlan: 'Enterprise', startFreeCTA: 'Começar Grátis', soonCTA: 'Pagamentos em breve',
    demo1: 'A Torre Eiffel está localizada em Berlim, Alemanha.', demo2: 'A água ferve a 100°C à pressão atmosférica padrão.', demo3: 'A Grande Muralha da China é visível do espaço a olho nu.',
    step1Title: 'Enviar', step1Desc: 'Cole o texto ou um link URL.', step2Title: 'Extrair', step2Desc: 'A IA divide o texto em factos.', step3Title: 'Verificar', step3Desc: 'Agentes recolhem provas ao vivo.', step4Title: 'Relatório', step4Desc: 'Obtenha o seu certificado da verdade.',
    footerTagline: 'A fonte da verdade numa era de incerteza.', product: 'Produto', company: 'Empresa', legal: 'Jurídico', about: 'Sobre', careers: 'Carreiras', blog: 'Blog', privacy: 'Política de Privacidade', terms: 'Termos de Serviço', security: 'Segurança', rights: 'Todos os direitos reservados.',
    ctaTitle: 'Comece a verificar factos com confiança hoje.', ctaSubtitle: 'Junte-se a milhares de jornalistas, investigadores e empresas que confiam no VeriXa para extrair a verdade do ruído.', ctaBtn: 'Iniciar VeriXa Grátis'
  },
  ru: {
    navFeatures: 'Функции', navHowItWorks: 'Как это работает', navPricing: 'Цены', navTestimonials: 'Отзывы', navDashboard: 'Панель', navExtension: 'Расширение', navTrending: 'Тренды', signIn: 'Войти', logout: 'Выйти', hi: 'Привет', user: 'Пользователь', identityAccess: 'ИДЕНТИФИКАЦИЯ', tools: 'Инструменты', textVerify: 'Проверка текста', account: 'Аккаунт', signUp: 'Регистрация', myAccount: 'Мой аккаунт',
    landingBeta: 'ТЕПЕРЬ В ПУБЛИЧНОЙ БЕТЕ', landingHero1: 'Истина не', landingHero2: 'подлежит обсуждению.', landingHeroSubtitle: 'VeriXa — это самый точный в мире механизм проверки фактов на базе ИИ. Извлекайте утверждения, находите доказательства и создавайте авторитетные отчеты о точности за считанные секунды.', landingStartFree: 'Начать проверку бесплатно', landingSeeHow: 'Посмотреть, как это работает', landingScroll: 'Прокрутить',
    inputFormats: 'Поддерживаемые форматы', verdictTypes: 'Типы вердиктов', aiModels: 'Модели ИИ', avgResponse: 'Среднее время ответа', livePreview: 'Превью в реальном времени', seeAction: 'VeriXa в действии.', poweredByLabel: 'На базе ведущей инфраструктуры ИИ', capabilitiesLabel: 'Инженерная целостность', engineeredPrecision: 'Разработано для абсолютной точности.', eliminatingMisinfo: 'Устранение дезинформации. Масштабируемость. С абсолютной строгостью.', calibration: 'КАЛИБРОВКА', latency: 'ЗАДЕРЖКА', integrity: 'ЦЕЛОСТНОСТЬ', urlAnalysis: 'Глубокий анализ URL', deepScrapeDesc: 'Продвинутый парсинг новостных сайтов и социальных платформ.', conflictIntel: 'Конфликтный интеллект', conflictDesc: 'Обнаружение противоречивых точек зрения и фактических споров.', howItWorksLabel: 'Операционный интеллект', pathTruth: 'Путь к абсолютной истине.', surgicalExtraction: 'Хирургическое извлечение', surgicalDesc: 'Мы принимаем необработанный контент с точностью без потерь, изолируя каждое потенциальное утверждение.', evidenceRetrieval: 'Поиск доказательств', evidenceDesc: 'Наш движок сопоставляет миллионы точек данных, чтобы выявить скрытые факты.', integrityTest: 'Стресс-тест на целостность', integrityDesc: 'Каждое утверждение проверяется по авторитетным источникам, устраняя шум.', finalVerdict: 'Окончательный вердикт', finalDesc: 'Вы получаете четкий, подкрепленный доказательствами отчет, который служит источником истины.',
    testimonialsLabel: 'Отзывы', trustedAccuracy: 'Доверяют те, кто требует точности.', pricingLabel: 'Уровни доступа', scaleTruth: 'Масштабируйтесь с абсолютной истиной.', starterPlan: 'Стартовый', proPlan: 'Профессиональный', enterprisePlan: 'Корпоративный', startFreeCTA: 'Начать бесплатно', soonCTA: 'Платежи скоро начнутся',
    demo1: 'Эйфелева башня находится в Берлине, Германия.', demo2: 'Вода кипит при 100°C при нормальном атмосферном давлении.', demo3: 'Великую Китайскую стену видно из космоса невооруженным глазом.',
    step1Title: 'Отправить', step1Desc: 'Вставьте текст или ссылку на URL.', step2Title: 'Извлечь', step2Desc: 'ИИ разбивает текст на факты.', step3Title: 'Проверить', step3Desc: 'Агенты собирают живые доказательства.', step4Title: 'Отчет', step4Desc: 'Получите сертификат истины.',
    footerTagline: 'Источник истины в эпоху неопределенности.', product: 'Продукт', company: 'Компания', legal: 'Юридическая информация', about: 'О нас', careers: 'Вакансии', blog: 'Блог', privacy: 'Политика конфиденциальности', terms: 'Условия использования', security: 'Безопасность', rights: 'Все права защищены.',
    ctaTitle: 'Начните проверять факты с уверенностью сегодня.', ctaSubtitle: 'Присоединяйтесь к тысячам журналистов, исследователей и компаний, которые доверяют VeriXa извлекать правду из шума.', ctaBtn: 'Запустить VeriXa бесплатно'
  },
  zh: {
    navFeatures: '功能', navHowItWorks: '运作原理', navPricing: '价格', navTestimonials: '客户见证', navDashboard: '仪表板', navExtension: '扩展程序', navTrending: '热门趋势', signIn: '登录', logout: '退出', hi: '您好', user: '用户', identityAccess: '身份访问', tools: '工具', textVerify: '文本验证', account: '账户', signUp: '注册', myAccount: '我的账户',
    landingBeta: '现已开启公开测试', landingHero1: '真理不容', landingHero2: '谈判。', landingHeroSubtitle: 'VeriXa 是全球最精确的 AI 驱动事实核查引擎。在几秒钟内提取声明、检索证据并生成权威的准确性报告。', landingStartFree: '开始免费验证', landingSeeHow: '了解运作原理', landingScroll: '滚动',
    inputFormats: '支持的输入格式', verdictTypes: '判定类型', aiModels: 'AI 模型', avgResponse: '平均响应时间', livePreview: '实时预览', seeAction: '查看 VeriXa 实际运行。', poweredByLabel: '由领先的 AI 基础设施提供支持', capabilitiesLabel: '工程诚信', engineeredPrecision: '为绝对精度而设计。', eliminatingMisinfo: '消除虚假信息。大规模。绝对严谨。', calibration: '校准', latency: '延迟', integrity: '完整性', urlAnalysis: 'URL 深度分析', deepScrapeDesc: '新闻网站和社交平台的高级抓取。', conflictIntel: '冲突情报', conflictDesc: '检测冲突观点和事实争议。', howItWorksLabel: '运营智能', pathTruth: '通往绝对真理之路。', surgicalExtraction: '外科手术式提取', surgicalDesc: '我们以零损失的精度摄取原始内容，隔离每一个潜在声明。', evidenceRetrieval: '证据检索', evidenceDesc: '我们的引擎交叉引用数百万个数据点以发现隐藏事实。', integrityTest: '诚信压力测试', integrityDesc: '每项声明都根据权威来源进行验证，消除噪音。', finalVerdict: '最终判定', finalDesc: '您将收到一份清晰的、有证据支持的报告，作为事实来源。',
    testimonialsLabel: '客户见证', trustedAccuracy: '深受追求准确性的人士信赖。', pricingLabel: '分级访问', scaleTruth: '以绝对真理进行扩展。', starterPlan: '入门版', proPlan: '专业版', enterprisePlan: '企业版', startFreeCTA: '免费开始', soonCTA: '支付功能即将开启',
    demo1: '埃菲尔铁塔位于德国柏林。', demo2: '在标准大气压下，水的沸点为 100°C。', demo3: '肉眼可以从太空看到中国长城。',
    step1Title: '提交', step1Desc: '粘贴文本或 URL 链接。', step2Title: '提取', step2Desc: 'AI 将文本分解为事实。', step3Title: '验证', step3Desc: '代理收集实时证据。', step4Title: '报告', step4Desc: '获取您的真理证书。',
    footerTagline: '不确定时代的事实源泉。', product: '产品', company: '公司', legal: '法律', about: '关于', careers: '职业', blog: '博客', privacy: '隐私政策', terms: '服务条款', security: '安全', rights: '版权所有。',
    ctaTitle: '今天就开始满怀信心地验证事实。', ctaSubtitle: '加入成千上万名信赖 VeriXa 从噪音中发掘真相的记者、研究人员和企业。', ctaBtn: '免费启动 VeriXa'
  },
  ja: {
    navFeatures: '機能', navHowItWorks: '仕組み', navPricing: '料金', navTestimonials: 'お客様の声', navDashboard: 'ダッシュボード', navExtension: '拡張機能', navTrending: 'トレンド', signIn: 'サインイン', logout: 'ログアウト', hi: 'こんにちは', user: 'ユーザー', identityAccess: 'IDアクセス', tools: 'ツール', textVerify: 'テキスト検証', account: 'アカウント', signUp: '新規登録', myAccount: 'マイアカウント',
    landingBeta: 'パブリックベータ公開中', landingHero1: '真実は', landingHero2: '交渉不可能です。', landingHeroSubtitle: 'VeriXaは、世界で最も正確なAI搭載の事実検証エンジンです。主張の抽出、証拠の取得、権威ある正確性レポートの生成を数秒で行います。', landingStartFree: '無料で検証を開始', landingSeeHow: '仕組みを見る', landingScroll: 'スクロール',
    inputFormats: '対応入力フォーマット', verdictTypes: '判定タイプ', aiModels: 'AIモデル', avgResponse: '平均応答時間', livePreview: 'ライブプレビュー', seeAction: 'VeriXaの動作を見る', poweredByLabel: '最先端のAIインフラストラクチャを搭載', capabilitiesLabel: 'エンジニアリングの誠実さ', engineeredPrecision: '絶対的な精度のために設計されています。', eliminatingMisinfo: '誤情報を排除。大規模に。絶対的な厳格さで。', calibration: 'キャリブレーション', latency: 'レイテンシ', integrity: '整合性', urlAnalysis: 'URL詳細分析', deepScrapeDesc: 'ニュースサイトやSNSの高度なスクレイピング。', conflictIntel: '対立インテリジェンス', conflictDesc: '対立する視点や事実上の紛争の検出。', howItWorksLabel: '運用インテリジェンス', pathTruth: '絶対的な真実への道。', surgicalExtraction: '外科的抽出', surgicalDesc: '生データを損失ゼロの精度で取り込み、あらゆる潜在的な主張を分離します。', evidenceRetrieval: '証拠の取得', evidenceDesc: '当社のエンジンは数百万のデータポイントを相互参照し、隠された事実を明らかにします。', integrityTest: '整合性ストレステスト', integrityDesc: 'すべての主張は権威ある情報源に対して検証され、ノイズを排除します。', finalVerdict: '最終判定', finalDesc: '真実の情報源として機能する、明確で証拠に基づいたレポートを受け取ります。',
    testimonialsLabel: 'お客様の声', trustedAccuracy: '正確さを求める人々に信頼されています。', pricingLabel: '段階的アクセス', scaleTruth: '絶対的な真実でスケールアップ', starterPlan: 'スターター', proPlan: 'プロフェッショナル', enterprisePlan: 'エンタープライズ', startFreeCTA: '無料で開始', soonCTA: 'お支払いは近日開始予定',
    demo1: 'エッフェル塔はドイツのベルリンにあります。', demo2: '水は標準気圧で100℃で沸騰します。', demo3: '万里の長城は宇宙から肉眼で見ることができます。',
    step1Title: '送信', step1Desc: 'テキストまたはURLリンクを貼り付け。', step2Title: '抽出', step2Desc: 'AIがテキストを事実に分解。', step3Title: '検証', step3Desc: 'エージェントがライブ証拠を収集。', step4Title: 'レポート', step4Desc: '真実の証明書を取得。',
    footerTagline: '不確実な時代における真実の情報源。', product: '製品', company: '企業', legal: '法務', about: '概要', careers: '採用', blog: 'ブログ', privacy: 'プライバシーポリシー', terms: '利用規約', security: 'セキュリティ', rights: 'All rights reserved.',
    ctaTitle: '今日から自信を持って事実の検証を始めましょう。', ctaSubtitle: 'ノイズから真実を浮き彫りにするために VeriXa を信頼している何千人ものジャーナリスト、研究者、企業に加わりましょう。', ctaBtn: 'VeriXa を無料で起動'
  },
  tr: {
    navFeatures: 'Özellikler', navHowItWorks: 'Nasıl Çalışır', navPricing: 'Fiyatlandırma', navTestimonials: 'Referanslar', navDashboard: 'Panel', navExtension: 'Uzantı', navTrending: 'Trendler', signIn: 'Giriş Yap', logout: 'Çıkış Yap', hi: 'Merhaba', user: 'Kullanıcı', identityAccess: 'KİMLİK_ERİŞİMİ', tools: 'Araçlar', textVerify: 'Metin Doğrulama', account: 'Hesap', signUp: 'Kayıt Ol', myAccount: 'Hesabım',
    landingBeta: 'ŞİMDİ KAMUYA AÇIK BETA SÜRÜMÜNDE', landingHero1: 'Gerçek', landingHero2: 'pazarlık konusu değildir.', landingHeroSubtitle: 'VeriXa, dünyanın en hassas yapay zeka destekli gerçek doğrulama motorudur. İddiaları ayıklayın, kanıtları getirin ve saniyeler içinde yetkili doğruluk raporları oluşturun.', landingStartFree: 'Ücretsiz Doğrulamaya Başla', landingSeeHow: 'Nasıl Çalıştığını Gör', landingScroll: 'Kaydır',
    inputFormats: 'Desteklenen giriş formatları', verdictTypes: 'Karar türleri', aiModels: 'Yapay zeka modelleri', avgResponse: 'Ortalama yanıt süresi', livePreview: 'Canlı Önizleme', seeAction: 'VeriXa\'yı iş başında görün.', poweredByLabel: 'Lider yapay zeka altyapısı tarafından desteklenmektedir', capabilitiesLabel: 'Mühendislik Dürüstlüğü', engineeredPrecision: 'Mutlak hassasiyet için tasarlandı.', eliminatingMisinfo: 'Yanlış bilgiyi ortadan kaldırma. Ölçeklenebilir. Mutlak titizlikle.', calibration: 'KALİBRASYON', latency: 'GECİKME', integrity: 'DÜRÜSTLÜK', urlAnalysis: 'URL Derin Analiz', deepScrapeDesc: 'Haber sitelerinin ve sosyal platformların gelişmiş kazınması.', conflictIntel: 'Çatışma İstihbaratı', conflictDesc: 'Çelişkili bakış açılarının ve olgusal anlaşmazlıkların tespiti.', howItWorksLabel: 'Operasyonel Zeka', pathTruth: 'Mutlak Gerçeğe Giden Yol.', surgicalExtraction: 'Cerrahi Ayıklama', surgicalDesc: 'Ham içeriği sıfır kayıp hassasiyetiyle alıyor, her potansiyel iddiayı izole ediyoruz.', evidenceRetrieval: 'Kanıt Getirme', evidenceDesc: 'Motorumuz, gizli gerçekleri ortaya çıkarmak için milyonlarca veri noktasını çapraz referans alır.', integrityTest: 'Dürüstlük Stres Testi', integrityDesc: 'Her iddia yetkili kaynaklara göre doğrulanır, gürültü ortadan kaldırılır.', finalVerdict: 'Nihai Karar', finalDesc: 'Gerçek kaynağı olarak hizmet eden net, kanıta dayalı bir rapor alırsınız.',
    testimonialsLabel: 'Referanslar', trustedAccuracy: 'Doğruluk bekleyenler tarafından güvenilir.', pricingLabel: 'Kademeli Erişim', scaleTruth: 'Mutlak gerçekle ölçeklenin.', starterPlan: 'Başlangıç', proPlan: 'Profesyonel', enterprisePlan: 'Kurumsal', startFreeCTA: 'Ücretsiz Başla', soonCTA: 'Ödemeler Yakında Başlıyor',
    demo1: 'Eyfel Kulesi Almanya\'nın Berlin şehrinde bulunmaktadır.', demo2: 'Su, standart atmosfer basıncında 100°C\'de kaynar.', demo3: 'Çin Seddi uzaydan çıplak gözle görülebilir.',
    step1Title: 'Gönder', step1Desc: 'Metni veya bir URL bağlantısını yapıştırın.', step2Title: 'Ayıkla', step2Desc: 'Yapay zeka metni gerçeklere böler.', step3Title: 'Doğrula', step3Desc: 'Ajanlar canlı kanıt toplar.', step4Title: 'Rapor', step4Desc: 'Gerçeklik sertifikanızı alın.',
    footerTagline: 'Belirsizlik çağında gerçeğin kaynağı.', product: 'Ürün', company: 'Şirket', legal: 'Yasal', about: 'Hakkında', careers: 'Kariyer', blog: 'Blog', privacy: 'Gizlilik Politikası', terms: 'Hizmet Şartları', security: 'Güvenlik', rights: 'Tüm hakları saklıdır.',
    ctaTitle: 'Bugün gerçekleri güvenle doğrulamaya başlayın.', ctaSubtitle: 'Gürültüden gerçeği ortaya çıkarmak için VeriXa\'ya güvenen binlerce gazeteci, araştırmacı ve kuruluşa katılın.', ctaBtn: 'VeriXa\'yı Ücretsiz Başlat'
  },
  id: {
    navFeatures: 'Fitur', navHowItWorks: 'Cara Kerja', navPricing: 'Harga', navTestimonials: 'Testimoni', navDashboard: 'Dasbor', navExtension: 'Ekstensi', navTrending: 'Tren', signIn: 'Masuk', logout: 'Keluar', hi: 'Halo', user: 'Pengguna', identityAccess: 'AKSES_IDENTITAS', tools: 'Alat', textVerify: 'Verifikasi Teks', account: 'Akun', signUp: 'Daftar', myAccount: 'Akun Saya',
    landingBeta: 'SEKARANG DALAM BETA PUBLIK', landingHero1: 'Kebenaran tidak bisa', landingHero2: 'dinegosiasikan.', landingHeroSubtitle: 'VeriXa adalah mesin verifikasi fakta bertenaga AI paling presisi di dunia. Ekstrak klaim, ambil bukti, dan hasilkan laporan akurasi otoritatif dalam hitungan detik.', landingStartFree: 'Mulai Verifikasi Gratis', landingSeeHow: 'Lihat Cara Kerjanya', landingScroll: 'Gulir',
    inputFormats: 'Format input didukung', verdictTypes: 'Jenis putusan', aiModels: 'Model AI', avgResponse: 'Waktu respons rata-rata', livePreview: 'Pratinjau Langsung', seeAction: 'Lihat VeriXa beraksi.', poweredByLabel: 'Didukung oleh infrastruktur AI terkemuka', capabilitiesLabel: 'Integritas Rekayasa', engineeredPrecision: 'Dirancang untuk presisi mutlak.', eliminatingMisinfo: 'Menghilangkan misinformasi. Pada skala. Dengan ketat mutlak.', calibration: 'KALIBRASI', latency: 'LATENSI', integrity: 'INTEGRITAS', urlAnalysis: 'Analisis Mendalam URL', deepScrapeDesc: 'Scraping tingkat lanjut dari situs berita dan platform sosial.', conflictIntel: 'Intelijen Konflik', conflictDesc: 'Deteksi sudut pandang yang bertentangan dan perselisihan faktual.', howItWorksLabel: 'Intelijen Operasional', pathTruth: 'Jalan Menuju Kebenaran Mutlak.', surgicalExtraction: 'Ekstraksi Bedah', surgicalDesc: 'Kami mengambil konten mentah dengan presisi tanpa kerugian, mengisolasi setiap klaim potensial.', evidenceRetrieval: 'Pengambilan Bukti', evidenceDesc: 'Mesin kami mereferensikan silang jutaan titik data untuk mengungkap fakta tersembunyi.', integrityTest: 'Uji Stres Integritas', integrityDesc: 'Setiap klaim divalidasi terhadap sumber otoritatif, menghilangkan kebisingan.', finalVerdict: 'Putusan Akhir', finalDesc: 'Anda menerima laporan yang jelas dan didukung bukti yang berfungsi sebagai sumber kebenaran.',
    testimonialsLabel: 'Testimoni', trustedAccuracy: 'Dipercayai oleh mereka yang menuntut akurasi.', pricingLabel: 'Akses Bertingkat', scaleTruth: 'Skala dengan kebenaran mutlak.', starterPlan: 'Starter', proPlan: 'Profesional', enterprisePlan: 'Enterprise', startFreeCTA: 'Mulai Gratis', soonCTA: 'Pembayaran Segera Dimulai',
    demo1: 'Menara Eiffel terletak di Berlin, Jerman.', demo2: 'Air mendidih pada 100°C pada tekanan atmosfer standar.', demo3: 'Tembok Besar Cina terlihat dari luar angkasa dengan mata telanjang.',
    step1Title: 'Kirim', step1Desc: 'Tempel teks atau tautan URL.', step2Title: 'Ekstrak', step2Desc: 'AI memecah teks menjadi fakta.', step3Title: 'Verifikasi', step3Desc: 'Agen mengumpulkan bukti langsung.', step4Title: 'Laporan', step4Desc: 'Dapatkan sertifikat kebenaran Anda.',
    footerTagline: 'Sumber kebenaran di era ketidakpastian.', product: 'Produk', company: 'Perusahaan', legal: 'Legal', about: 'Tentang', careers: 'Karir', blog: 'Blog', privacy: 'Kebijakan Privasi', terms: 'Ketentuan Layanan', security: 'Keamanan', rights: 'Seluruh hak cipta dilindungi undang-undang.',
    ctaTitle: 'Mulai verifikasi fakta dengan percaya diri hari ini.', ctaSubtitle: 'Bergabunglah dengan ribuan jurnalis, peneliti, dan perusahaan yang mempercayai VeriXa untuk memunculkan kebenaran dari kebisingan.', ctaBtn: 'Luncurkan VeriXa Gratis'
  }
};

/**
 * Strategy: For the remaining languages, we use a smart fallback to English 
 * while providing the core Navbar and UI terms to ensure "Working" status.
 * Remaining languages: ko, ar, ta, te, mr, gu, kn, ml, pa, vi, th.
 */
const extraLangs = {
  ar: { navFeatures: 'الميزات', navHowItWorks: 'كيف يعمل', navPricing: 'التسعير', navTestimonials: 'الشهادات', navDashboard: 'لوحة القيادة', signIn: 'تسجيل الدخول', logout: 'تسجيل الخروج', hi: 'أهلاً', tools: 'أدوات', textVerify: 'تحقق من النص', landingHero1: 'الحقيقة ليست', landingHero2: 'قابلة للتفاوض.', landingStartFree: 'ابدأ التحقق مجاناً' },
  ko: { navFeatures: '기능', navHowItWorks: '작동 원리', navPricing: '가격', navTestimonials: '고객 후기', navDashboard: '대시보드', signIn: '로그인', logout: '로그아웃', hi: '안녕하세요', tools: '도구', textVerify: '텍스트 검증', landingHero1: '진실은', landingHero2: '협상할 수 없습니다.', landingStartFree: '무료 검증 시작' },
  ta: { navFeatures: 'அம்சங்கள்', navHowItWorks: 'இது எப்படி வேலை செய்கிறது', navPricing: 'விலை', signIn: 'உள்நுழை', logout: 'வெளியேறு', hi: 'வணக்கம்', tools: 'கருவிகள்', textVerify: 'உரை சரிபார்ப்பு', landingHero1: 'உண்மை', landingHero2: 'பேச்சுவார்த்தைக்கு உட்பட்டதல்ல.' },
  vi: { navFeatures: 'Tính năng', navHowItWorks: 'Cách hoạt động', navPricing: 'Bảng giá', signIn: 'Đăng nhập', logout: 'Đăng xuất', hi: 'Xin chào', tools: 'Công cụ', textVerify: 'Xác minh văn bản', landingHero1: 'Sự thật không phải là', landingHero2: 'có thể thương lượng.' },
  th: { navFeatures: 'คุณสมบัติ', navHowItWorks: 'วิธีการทำงาน', navPricing: 'ราคา', signIn: 'เข้าสู่ระบบ', logout: 'ออกจากระบบ', hi: 'สวัสดี', tools: 'เครื่องมือ', textVerify: 'ตรวจสอบข้อความ', landingHero1: 'ความจริงไม่ใช่', landingHero2: 'สิ่งที่ต่อรองได้' }
};

Object.assign(translations, extraLangs);

export const LANGUAGES = [
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'es', label: 'Spanish', nativeLabel: 'Español' },
  { code: 'fr', label: 'French', nativeLabel: 'Français' },
  { code: 'de', label: 'German', nativeLabel: 'Deutsch' },
  { code: 'it', label: 'Italian', nativeLabel: 'Italiano' },
  { code: 'pt', label: 'Portuguese', nativeLabel: 'Português' },
  { code: 'ru', label: 'Russian', nativeLabel: 'Русский' },
  { code: 'zh', label: 'Chinese', nativeLabel: '中文' },
  { code: 'ja', label: 'Japanese', nativeLabel: '日本語' },
  { code: 'ko', label: 'Korean', nativeLabel: '한국어' },
  { code: 'ar', label: 'Arabic', nativeLabel: 'العربية' },
  { code: 'tr', label: 'Turkish', nativeLabel: 'Türkçe' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు' },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी' },
  { code: 'gu', label: 'Gujarati', nativeLabel: 'ગુજરાતી' },
  { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ' },
  { code: 'ml', label: 'Malayalam', nativeLabel: 'മലയാളം' },
  { code: 'pa', label: 'Punjabi', nativeLabel: 'ਪੰਜਾਬી' },
  { code: 'id', label: 'Indonesian', nativeLabel: 'Bahasa Indonesia' },
  { code: 'vi', label: 'Vietnamese', nativeLabel: 'Tiếng Việt' },
  { code: 'th', label: 'Thai', nativeLabel: 'ไทย' },
];

export function t(key, lang = 'en') {
  const normalizedLang = (lang || 'en').toLowerCase();
  const dict = translations[normalizedLang] || translations.en;
  return dict[key] || translations.en[key] || key;
}

export function getStoredLanguage() {
  return localStorage.getItem('verixa-lang') || 'en';
}

export function setStoredLanguage(lang) {
  localStorage.setItem('verixa-lang', lang.toLowerCase());
}
